# Config settings
title: Health Data Review
baseurl: "data-sources-review"
permalink: /:title.htm

# Search settings
tipue_search:
  exclude:
    files: [search.html, about.html]

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
