# Config settings
title: Health Data Review
baseurl: "/pdh_data_review"

collections:
  datasets:
    output: true
    permalink: /:path/:title:output_ext

# Search settings
tipue_search:
  include:
    pages: true
    collections: [datasets]
  exclude:
    files: [search.html]

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
